{% set name = "cortecs" %}
{% set version = "1.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/cortecs-{{ version }}.tar.gz
  sha256: 3733912853d79c5f80c734a146c33cad7f9e164f9fa4d11e76094d7d27e81ae6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
  host:
    - python >=3.9,<3.12
    - pip
  run:
    - python >=3.9,<3.12
    - numpy
    - jax >=0.4.20,<0.5.0
    - tqdm
    - h5py >=3.0
    - tensorflow-base <=2.15.0.post1
    - tensorflow-estimator
    - matplotlib-base
    - pandas

test:
  imports:
    - cortecs
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/arjunsavel/cortecs
  summary: Compress opacity for radiative transfer in exoplanet cross-correlation studies
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - arjunsavel
